console.log("🌐 Cloudflare Tunnel Alternative");
console.log("===============================");
console.log("If ngrok setup is complex, try Cloudflare Tunnel:");
console.log("");
console.log("1. Download cloudflared:");
console.log("   https://github.com/cloudflare/cloudflared/releases");
console.log("   Download: cloudflared-windows-amd64.exe");
console.log("");
console.log("2. Run tunnel:");
console.log("   cloudflared tunnel --url http://localhost:5000");
console.log("");
console.log("3. Get URL:");
console.log("   Will show: https://random-words.trycloudflare.com");
console.log("");
console.log("4. Use in mobile app:");
console.log('   String baseUrl = "https://random-words.trycloudflare.com";');
console.log("");
console.log("✅ Benefits:");
console.log("- Free to use");
console.log("- No registration needed");
console.log("- HTTPS automatically");
console.log("- Works with mobile apps");
