console.log("📱 ANDROID EMULATOR FIX");
console.log("========================");
console.log("❌ Current URLs failing:");
console.log("  - localhost:5000 (Connection refused)");
console.log("  - 192.168.1.34:5000 (No route to host)");
console.log("  - 10.0.2.2:5000 (Timeout)");
console.log("");
console.log("✅ SOLUTION:");
console.log("Use: http://10.0.2.2:5000");
console.log("");
console.log("🔧 CONFIGURATION:");
console.log("");
console.log("Flutter/Dart:");
console.log('String baseUrl = "http://10.0.2.2:5000";');
console.log("");
console.log("For Android Emulator ONLY:");
console.log("- 10.0.2.2 = Host computer");
console.log("- localhost = Emulator itself");
console.log("- 192.168.1.34 = Network issue");
console.log("");
console.log("🧪 TEST:");
console.log("1. Update mobile app to use 10.0.2.2:5000");
console.log("2. Restart the app");
console.log("3. Try OTP again");
console.log("");
console.log("🎯 Expected Result:");
console.log("Mobile App → http://10.0.2.2:5000/api/auth/send-otp ✅");
console.log("Backend → Receives request ✅");
console.log("SMS → Sent to your phone ✅");
