console.log("🔧 NETWORK TROUBLESHOOTING");
console.log("============================");
console.log("✅ Server Status: RUNNING");
console.log("📍 Server IP: 192.168.1.34:5000");
console.log("📱 Mobile Error: No route to host");
console.log("");
console.log("🔍 POSSIBLE CAUSES:");
console.log("1. Different WiFi networks");
console.log("2. Firewall blocking connection");
console.log("3. Mobile VPN enabled");
console.log("4. IP address changed");
console.log("5. Backend firewall issues");
console.log("");
console.log("💡 SOLUTIONS:");
console.log("");
console.log("📱 CHECK MOBILE DEVICE:");
console.log("- Same WiFi as computer?");
console.log("- VPN turned off?");
console.log("- Firewall disabled?");
console.log("- Correct IP address?");
console.log("");
console.log("💻 CHECK COMPUTER:");
console.log("- Windows Firewall allowing port 5000?");
console.log("- Antivirus blocking connections?");
console.log("- Server still running?");
console.log("");
console.log("🧪 TEST CONNECTION:");
console.log("curl http://192.168.1.34:5000");
console.log("Should return: {'success':true,'message':'Batter Delivery API is running'}");
console.log("");
console.log("🔄 ALTERNATIVE APPROACH:");
console.log("Use localhost for development");
console.log("Update mobile app to use: http://localhost:5000");
console.log("Only works for mobile emulator on same machine");
